export const homeData = [
    {
      id: 1,
      name: "I may destroy you",
      rating: 4.7,
      time: "1 temporada",
      desc: "Arabella (Michaela Coel) é uma mulher segura de si que precisa questionar e reconstruir sua vida após um episódio de abuso sexual.",
      starring: "Michaela Coel, Paapa Essiedu, Weruche Opia, Karan Gill",
      genres: "Drama",
      tags: "Drama",
      cover:"https://static.hbo.com/I-may-destroy-you-ka-1920.jpg",
      video: "https://www.youtube.com/embed/DTjlurdbNnw?si=KToDN5ywXBWLVByW",
      date: "2020",
    },
    {
      id: 2,
      name: "Aftersun",
      rating: 4.6,
      time: "2h22mins",
      desc: "Sophie reflete sobre a alegria e a melancolia das férias que ela tirou com seu pai 20 anos antes. Memórias reais e imaginárias preenchem as lacunas enquanto ela tenta reconciliar o pai que conheceu com o homem que desconhecia.",
      starring: "Paul Mescal, Frankie Corio, Celia Rowlson Hall",
      genres: "Drama",
      tags: "Drama",
      cover: "https://www.youtube.com/embed/DTjlurdbNnw?si=KToDN5ywXBWLVByW",
      video: "../video/video2.mp4",
      date: "2022",
    },
    {
      id: 3,
      name: "Six Feet Under",
      rating: 4.8,
      time: "5 temporadas",
      desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
      starring: "James Chinlund, Jeff Nathanson",
      genres: "Adventures",
      tags: "Adventures,Action ",
      cover: "https://deliriumnerd.com/wp-content/uploads/2018/09/Six-Feet-Under-Gestorben-wird-immer.jpg",
      video: "../video/video3.mp4",
      date: "2001",
    },
    {
      id: 4,
      name: "burning",
      rating: 4.9,
      time: "2h28mins",
      desc: "Baseado no romance japonês “Barn Burning” de Haruki Murakami, o filme foca o triângulo amoroso formado por dois rapazes, Ben e Jong-su, e uma garota, Hae-mi.",
      starring: "Karen Gilchrist, James Earl Jones",
      genres: "Triller, Mistério",
      tags: "Action, Adventures, Horror",
      cover: "https://ims.com.br/wp-content/uploads/2018/12/burning-15_1920x1080.jpg",
      video: "../video/video4.mp4",
      date: "2018",
    },
  ]
  export const upcome = [
    {
      id: 1,
      cover: "https://www.washingtonblade.com/content/files/2024/04/Andrew_Scott_in_Ripley_insert_courtesy_Netflix.jpg",
      name: "Ripley",
      time: "8 episódios",
    },
    {
      id: 2,
      cover: "https://rollingstone.uol.com.br/media/_versions/zoe_kravitz_em_high_fidelity_-_divulgacao_hulufile_widelg.jpg",
      name: "High Fidelity",
      time: "1 temporada",
    },
    {
      id: 3,
      cover: "https://m.media-amazon.com/images/M/MV5BNDdjMGIxMWEtYWFiZC00ZWZjLWFhZGUtNTdjMmEzYWVlMmRjXkEyXkFqcGdeQXNuZXNodQ@@._V1_.jpg",
      name: "The Rings of Power",
      time: "1 temporada",
    },
    {
      id: 4,
      cover: "https://images.thedirect.com/media/article_full/abbb.jpg",
      name: "Abbott Elementary",
      time: "3 temporadas",
    },
    {
      id: 5,
      cover: "https://miro.medium.com/v2/resize:fit:1200/0*bsCRIEXecIrIM3l2.png",
      name: "Normal People",
      time: "1 temporada",
    },
  ]
  export const latest = [
    {
      id: 1,
      cover: "https://www.planocritico.com/wp-content/uploads/9015/08/plano-cr%C3%ADtico-o-s%C3%A9timo-selo-filme-.jpg",
      name: "O sétimo selo",
      time: "1h36min",
    },
    {
      id: 2,
      cover: "https://media.newyorker.com/photos/62016b79871efcf597d51bea/master/pass/Brody-WorstPerson-World.jpg",
      name: "The worst person in the world",
      time: "2h1min",
    },
    {
      id: 3,
      cover: "https://www.cnnbrasil.com.br/wp-content/uploads/sites/12/2024/06/flashdance-filme.webp?w=1200&h=674&crop=1g",
      name: "Flashdance",
      time: "1h35min",
    },
    {
      id: 4,
      cover: "https://d1tgyzt3mf06m9.cloudfront.net/v3-staging/2023/11/Feature-34-scaled.jpg",
      name: "Past Lives",
      time: "2hr : 38mins",
    },
    {
      id: 5,
      cover: "https://assets.mubicdn.net/images/notebook/post_images/27814/images-w1400.jpg?1552424103",
      name: "Microhabitat",
      time: "1h46min",
    },
  ]
  
  export const trending = [
    {
      id: 1,
      name: "The Dinosaur",
      rating: 4.7,
      time: "2hr : 22mins",
      desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
      starring: "Karen Gilchrist, James Earl Jones",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "../images/img/slide1.png",
      date: "20-Jan-1997",
    },
    {
      id: 2,
      name: "The Great Emperor",
      rating: 4.6,
      time: "2hr : 22mins",
      desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
      starring: "Brenda Chapman, Jeff Nathanson",
      genres: "Adventures",
      tags: "Adventures,Animation,Family",
      cover: "../images/img/slide2.jpg",
      date: "10-JUL-2021",
    },
    {
      id: 3,
      name: "Jumbo Queen",
      rating: 4.8,
      time: "2hr : 22mins",
      desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
      starring: "James Chinlund, Jeff Nathanson",
      genres: "Adventures",
      tags: "Adventures,Action ",
      cover: "../images/img/slide3.jpg",
      date: "20-FEB-2010",
    },
  ]
  export const recommended = [
    {
      id: 4,
      cover: "../images/rec/rec1.jpg",
      name: "One Man Army",
      time: "2hr : 38mins",
    },
    {
      id: 5,
      cover: "../images/rec/rec2.jpg",
      name: "Jumbo Queen",
      time: "2hr : 38mins",
    },
    {
      id: 1,
      cover: "../images/rec/rec3.jpg",
      name: "My office Boss",
      time: "2hr : 38mins",
    },
    {
      id: 2,
      cover: "../images/rec/rec4.jpg",
      name: "Shadowe",
      time: "2hr : 38mins",
    },
    {
      id: 3,
      cover: "../images/upcome/u3.jpg",
      name: "Another Danger",
      time: "2hr : 38mins",
    },
  ]